CastXML/pygccxml

README.rst
This PR updates the link of the QuantifiedCode badge. See quantifiedcode/issues#5.
=> update the URL of the QuantifiedCode badge

pygccxml/parser/config.py
Use ConfigParser instead. Add support for cflags property in config files.
=> SafeConfigParser is deprecated in python 3.2 and newer

pygccxml/parser/source_reader.py
Just putting in "-std=c++11" in cflags is not sufficient. Without this change, I get errors like these:
```
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/stdexcept:45:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__config:234:20: error: 
cannot combine with previous 'char16_t' declaration specifier
typedef __char16_t char16_t;
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__config:235:20: error: 
cannot combine with previous 'char32_t' declaration specifier
typedef __char32_t char32_t;
^
2 errors generated.
```
This fix should probably generalized to cover C++14 and C++17 as well.
=> pass C++11 flag to castxml

unittests/autoconfig.py, unittests/data/remove_template_defaults.hpp, unittests/parser_test_case.py
`parser_test_case.py`
* Monkey-patch `assertIn` and `assertNotIn` methods for Python2.6
`remove_template_defaults.hpp`
* Use `std::tr1` unordered containers for gcc >= 4.4.7 and castxml
* I've tested the following combinations
* gcc 4.4.7 + gccxml
* gcc 4.9 + castxml
`autoconfig.py`
* Cosmetic fix for generator name printed to stdout when launching unit tests
=> Python2.6 compatibility and gcc + castxml fixes

pygccxml/binary_parsers/undname.py, pygccxml/parser/scanner.py
`undname_creator_t.format_argtypes` contained an undefined variable named `type_`.
Comment spelling fix in `scanner.py`
=> Typo fixes

pygccxml/declarations/__init__.py, pygccxml/parser/scanner.py, unittests/data/classes.hpp, unittests/declaration_matcher_tester.py
Unlike GCCXML, CastXML creates two distinct XML nodes for a typedef of
the form
typedef (class|struct) {} foo;
The first XML node is an unnamed class/struct and the second is a
typedef that refers to the first node. This requires special handling
during parsing so that the name of the typedef is propagated to the
class/struct.
=> Fix for typedef'd unnamed class/struct

pygccxml/parser/patcher.py, unittests/data/patcher.hpp, unittests/patcher_tester.py
CastXML currently doesn't modify enum names used in default arguments for
functions, it simply uses the same text present in the source file. This
causes compilation failures in bindings generated by pyplusplus in case
of code such as the following:
namespace ns1
{
namespace ns2
{
enum color { red };
void foo(color arg = ns2::red);
}
}
In this case, CastXML produces `ns2::red` as the default value while
GCCXML removes the namespace name and sets the default value to `red`.
pygccxml's patcher for unqualified names expects GCCXML's behavior, so
it fails to detect the CastXML output as one needing further
qualification.
Consequently, pyplusplus refers to the default value as `ns2::red`,
which fails compilation because the name needs to be fully qualified as
`ns1::ns2::red`. This fix produces …
=> Fix unqualified enums in default arguments for CastXML

pygccxml/parser/scanner.py, pygccxml/utils/__init__.py, unittests/patcher_tester.py
CastXML's output for default arguments for function parameters was
modified in response to CastXML/CastXML#51. The tool now generates fully
qualified names in default arguments, so we need to check the
`cvs_revision` attribute in the XML output to differentiate between the
different output formats.
=> Adapt patched output to CastXML cvs_revision 1.137

pygccxml/parser/patcher.py, unittests/data/patcher.hpp, unittests/patcher_tester.py
CastXML currently doesn't modify integral constant names used in default
arguments for functions, it simply uses the same text present in the source
file. This causes compilation failures in bindings generated by pyplusplus in
case of code such as the following:
struct st
{
static int const DEFAULT = 0;
void fun(int arg=DEFAULT);
};
In this case, CastXML produces `DEFAULT` as the default value while
GCCXML qualifies the name and sets the default value to `st::DEFAULT`.
Consequently, pyplusplus refers to the default value as `DEFAULT`, which
fails compilation because the name needs to be fully qualified as
`st::DEFAULT`. This fix produces the desired qualified output from
pygccxml with both GCCXML and CastXML.
=> Fix unqualified integral const in default arguments for CastXML

unittests/data/core_class_hierarchy.hpp
`core_class_hierarchy.hpp` contains classes with the following
inheritance hierarchy
derived_private_t -> base_t
multi_derived_t   -> derived_private_t, base_t
Since `multi_derived_t` contains `base_t` as a direct base and as a base
via `derived_private_t`, this creates warnings about `base_t` being
inaccessible because it's ambiguous which `base_t` instance is being
referred to.
Changed the inheritance hierarchy to `virtual` inheritance so that
`derived_private_t` and `multi_derived_t` inherit `base_t` virtually. Now
there's only a single instance of `base_t` in `multi_derived_t` and the
warning is avoided.
Fixes #46
Change-Id: I3a52a666460bea2cc3c66b1855288d757f93f507
=> Fix warning in core_class_hierarchy.hpp

pygccxml/parser/config.py, pygccxml/utils/utils.py
Code that uses the `which` command to find *castxml* and *clang++* now
pipes `stderr` in addition to `stdout`. This prevents error messages
from being printed if the executables being searched for are not on
`PATH`.
=> Pipe `stderr` when calling `subprocess.Popen`

unittests/data/free_operators.hpp, unittests/data/type_traits.hpp
`free_operators.hpp` had a couple of instances of narrowing conversions
within braced initializers, which is ill-formed since C++11.
`type_traits.hpp` had two instances of aggregates being
value-initialized using empty parentheses. Since these aggregates had
implicitly deleted default constructors (due to the presence of `const`
data members), value-initialization performs default-initialization,
which is ill-formed. We need aggregate-initialization to be performed,
so the initialization must use braces instead of parentheses for C++11
and later.
=> Fix errors in -std=c++11 mode

pygccxml/parser/patcher.py, pygccxml/parser/source_reader.py, pygccxml/utils/__init__.py, pygccxml/utils/utils.py, unittests/data/patcher.hpp, unittests/patcher_tester.py
Given the following code
namespace ns
{
enum color {red, green, blue};
void test( color arg=blue );
}
CastXML produces a fully qualified name for the default argument -
`::ns::color::blue`.
While this default argument string is valid for C++11 and later, and
indeed required if `color` were a scoped enumeration, the default
argument is invalid for C++03 code.
Prior to C++11, enumerator names were added to the enclosing scope, so
they could not be qualified using the enum-name. Hence, for C++03, the
default argument needs to be patched to say `::ns::blue`.
=> Fix patching of enums in default arguments for C++03

pygccxml/parser/source_reader.py
I changed the multi-line exception. FYI
`Exception, "message"` is not compatible with Python 3 (not sure about Python 2). The compatible way to write it is `Exception("message")`
I also made a small change to a part, as it was only giving the `gccxml_msg` (which was an empty string), so I thought giving a return code may be helpful. 
This resolves #57 
EDIT: Not entirely sure why the pep8 checks are failing. I didn't edit all that much...
I'll read over the log later
=> Various fixes for Windows

.travis.yml
Until a new release is pushed to pip, with a proper tag,
just use the current master. This fixes coverage upload
for windows builds.
=> Download latest appveyor-artifacts

pygccxml/parser/source_reader.py
This can get expanded the wrong way with VS9 leading to a compile error.
=> Fix _HAS_TR1=0 definition for msvc9

pygccxml/utils/utils.py
gcc/clang C++ standard version flags now support the -std=c++17 &
-std=c++2a flags, along with their "gnu" counterparts.
=> Add support for -std=c++17 & -std=c++2a flag

pygccxml/parser/source_reader.py
- MinGW isn't always installed in such a way that mingw is actually in the path to the compiler. Adding 'g++' and 'gcc' to the list of terms it looks for in the compiler path when on Windows helps finding all installation of the gnu compiler
=> Better support for the gnu compiler on Windows

pygccxml/parser/config.py
If you start the parser with a cmake custom command in windows, it could be that you find two paths of visual studio.
=> Fix where cl error in cmake environment

.github/workflows/tests.yml, .gitignore, docs/conf.py, docs/documentation.rst, docs/install.rst, setup.py, unittests/pep8_tester.py
- Use `setuputils.setup(..., extras_require)`
- Organize imports according to PEP8 (builtin, 3rd party, then 1st party)
For `extras_require`:
https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies
Saw this when looking at `trimesh`: https://github.com/mikedh/trimesh/blob/4cacbffcd9bd1a637bf05b638bc3376464e3577b/setup.py
For PEP8 imports:
https://www.python.org/dev/peps/pep-0008/#imports
=> install: Expose test + docs requirements, encourage use of virtualenv

.github/workflows/tests.yml
This branch provides a fix for the `codecov` failures. The previously generated `.coverage` file generated by running the `coverage` tool was in an invalid format for Github's `codecov`. This branch switches the format over to `xml`, which can be processed by `codecov`
=> Switch to xml for coverage reports

pygccxml/declarations/calldef.py, pygccxml/parser/scanner.py, unittests/data/test_overrides.hpp, unittests/test_all.py, unittests/test_overrides.py
Use the attr information called "overrides" to pass the declaration of
the function which is overridden by a declaration.
=> Use "overrides" information from CastXML

pygccxml/parser/config.py, unittests/test_all.py, unittests/test_warn_missing_include_dirs.py
Instead of raising a RunTime error on a missing include
directory, print a warning to the screen and allow processing to continue.
=> Warn if "include directories" do not exist

.github/workflows/tests.yml, pygccxml/declarations/declaration.py, pygccxml/parser/scanner.py, unittests/data/test_deprecation.hpp, unittests/test_all.py, unittests/test_deprecation.py
Pass the newly captured deprecation information from CastXML to the
declarations of those objects.
=> Add declaration object for deprecation message.

.binder/.dockerignore, .binder/Dockerfile, .binder/README.md, .dockerignore, README.rst, docs/examples/notebook/example.ipynb, setup.py
Towards #126
Preview Link:
https://mybinder.org/v2/gh/EricCousineau-TRI/pygccxml/feature-py-notebook-example?filepath=pygccxml/docs/examples/notebook/example.ipynb
=> Add simple example Jupyter notebook (for Binder)

pygccxml/parser/config.py, pygccxml/parser/source_reader.py, unittests/data/test_ccflags.hpp, unittests/test_all.py, unittests/test_ccflags.py
Allow users to pass predefined macros to the simulated compiler (e.g. `-fopenmp`). By default, these are removed by castxml. Currently only supported on mac and linux.
=> Handle default flags

pygccxml/parser/config.py
Fixes an issue introduced in 17feef3 where cflags aren't always passed to subclass.
=> Pass cflags to subclass

pygccxml/utils/utils.py
I find shutils only use PATH rather than sys.path. In jupyter it usually is the environment of the jupyter rather than the kernel. Adding this helps it search for castxml.
=> Add search_path arg

pygccxml/declarations/type_traits.py
On macOS 11.3 / Xcode 12.5 with castxml 0.4.3 installed via MacPorts, some uses of std::string were not correctly identified (the decl_string was `::std::basic_string<char,std::char_traits<char>,std::allocator<char>>`, without any spaces, which didn't match anything). This caused `decl_wrappers.python_traits.is_immutable` to return the wrong thing, which in turn caused `decl_wrappers.python_traits.call_traits` to generate broken code. This was a pain to track down. The responsible code seemed rather brittle. This is a simple attempt to make it slightly more robust.
=> Make type equivalence check for string and ostream more robust

CHANGELOG.md, README.rst
Follow up from https://github.com/CastXML/pygccxml/pull/159
=> Drop support for Python 3.6

src/pygccxml/declarations/container_traits.py, src/pygccxml/declarations/type_traits.py, src/pygccxml/parser/config.py, src/pygccxml/parser/linker.py, src/pygccxml/parser/project_reader.py, src/pygccxml/parser/scanner.py, src/pygccxml/utils/utils.py, unittests/find_container_traits_tester.py
We don't support Python 2 since a long time now
=> Deprecate utils.is_str

src/pygccxml/utils/utils.py
We do not support version below Python 3.7
=> Utils: drop _find_xml_generator_for_legacy_python

pyproject.toml
commit 97498ae39322fd228d10d5e099cbe11f97e9f384
Author:     Michał Górny <mgorny@gentoo.org>
AuthorDate: 2023-08-22 05:54:54 +0200
Commit:     Michał Górny <mgorny@gentoo.org>
CommitDate: 2023-08-22 05:55:20 +0200
Build: Remove redundant wheel dep from pyproject.toml
Remove the redundant `wheel` dependency, as it is added by the backend
automatically.  Listing it explicitly in the documentation was
a historical mistake and has been fixed since, see:
https://github.com/pypa/setuptools/commit/f7d30a9529378cf69054b5176249e5457aaf640a
commit df8e4074998afe15593bead59674ebdad9d59676
Author:     Michał Górny <mgorny@gentoo.org>
AuthorDate: 2023-08-22 05:50:07 +0200
Commit:     Michał Górny <mgorny@gentoo.org>
CommitDate: 2023-08-22 05:50:07 +0200
Build: Use non-legacy setuptools backend
Use the …
=> Build: pyproject.xml fixes

docs/install.rst, src/pygccxml/parser/config.py, unittests/array_bug_tester.py, unittests/test_argument_without_name.py, unittests/test_cpp_standards.py, unittests/test_map_gcc5.py, unittests/test_pattern_parser.py, unittests/test_smart_pointer.py, unittests/test_va_list_tag_removal.py, unittests/xml_generator.cfg
We don't support gccxml anymore
=> cleanup: remove old code related to gccxml

src/pygccxml/parser/config.py
Remove the `__get_first_compiler_in_path()` function that used `which(1)` / `where` program to get the compiler path, with built-in `shutil.which()`.  This fixes pygccxml on systems where `which(1)` is no longer present (it is not a standard POSIX tool, and Linux distributions are working towards making it optional).
=> Use `shutil.which()` to get compiler path

src/pygccxml/parser/scanner.py
This was sometimes a bool (for the False case) and sometimes a "1" string. This makes sure these variables always have the same type
=> calldef attributes: align to bool type

src/pygccxml/parser/scanner.py, tests/test_array_argument.py, unittests/data/test_array_argument.hpp
scanner.py: add support for "original_type" attribute of "Argument" XML tag. For array args this means avoiding losing the delcared width of the array and having its decl_type show as pointer_t.
Fall back on "type" (current default-no-matter-what) attribute when "original_type" is not present.
XML generated by pygccxml+CastXML:
Behaviour:
```python
classes_obj                       = global_ns.classes()
class_im_looking_for              = [d for d in classes_obj.declarations if "class_im_looking_for" in d.name][0]
method_im_looking_for_declaration = [d for d in class_im_looking_for.declarations if d.name == "method_name"][0]
method_arguments                  = method_im_looking_for_declaration.arguments
argument                          = method_arguments[0]
argument.decl_type.decl_string …
```
=> scanner.py: add support for "original_type" attribute of "Argument" XML tag

CHANGELOG.md, pyproject.toml
=> Bump version to 2.6.0

tests/data/core_types.hpp
Fixes:
---------------------------- Captured stderr setup ----------------------------- /<<PKGBUILDDIR>>/.pybuild/cpython3_3.12_pygccxml/build/tests/data/core_types.hpp:57:38: error: ISO C++17 does not allow dynamic exception specifications [-Wdynamic-exception-spec]
57 |         int some_function( double hi) const throw( exception ){
|                                             ^~~~~~~~~~~~~~~~~~
/<<PKGBUILDDIR>>/.pybuild/cpython3_3.12_pygccxml/build/tests/data/core_types.hpp:57:38: note: use 'noexcept(false)' instead
57 |         int some_function( double hi) const throw( exception ){
|                                             ^~~~~~~~~~~~~~~~~~
|                                             noexcept(false)
1 error generated.
-----
No need to keep the throws / or to replace it with …
=> tests: fix compilation with c++14/17

.github/workflows/tests.yml, tests/test_remove_template_defaults.py, tests/test_source_reader.py
=> ci: move to macos13

pyproject.toml, src/pygccxml/declarations/container_traits.py, src/pygccxml/declarations/type_traits.py
Add missing spaces, which should fix some equivalence detection in the defaults_eraser function
=> type-traits: fix string equivalences

tests/test_map_gcc5.py, tests/test_pattern_parser.py, tests/test_smart_pointer.py
Fixes:
/Applications/Xcode_15.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/cstdlib:144:9: error: no member named 'at_quick_exit' in the global namespace using ::at_quick_exit _LIBCPP_USING_IF_EXISTS;
~~^
/Applications/Xcode_15.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/cstdlib:145:9: error: no member named 'quick_exit' in the global namespace using ::quick_exit _LIBCPP_USING_IF_EXISTS;
~~^
=> tests: fix some tests on macOS

tests/test_cpp_standards.py, tests/test_overrides.py, tests/test_pattern_parser.py
Fixes:
/Applications/Xcode_15.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/cstdlib:144:9: error: no member named 'at_quick_exit' in the global namespace using ::at_quick_exit _LIBCPP_USING_IF_EXISTS;
~~^
/Applications/Xcode_15.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/cstdlib:145:9: error: no member named 'quick_exit' in the global namespace using ::quick_exit _LIBCPP_USING_IF_EXISTS;
~~^
2 errors generated.
=> tests: fix more tests on macOS

src/pygccxml/declarations/container_traits.py, src/pygccxml/declarations/pattern_parser.py, src/pygccxml/parser/scanner.py, tests/test_call_invocation.py, tests/test_find_container_traits.py, tests/test_remove_template_defaults.py, tests/test_templates.py, tests/test_variable_matcher.py, tests/test_vector_traits.py
I have seen different scenarios regarding spaces in templates.
On some platforms there might be spaces, on some others not.
The biggest changes are in:
src/pygccxml/parser/scanner.py -> replace spaces that are actually coming from the xml file
src/pygccxml/declarations/pattern_parser.py -> remove spaces
Of course all the tests had to be adjusted
This "might" be a breaking change if you used to compare declarations manually,
but from a pygccxml point of view all comparisons / search functions are still
working as before.
=> templates: fix issues with spaces

tests/test_va_list_tag_removal.py
With a newer clang/llvm setup, the va_list_tag definition is gone. I fixed the test quickly, it's not perfect, but it passes now locally and on CI.
I think I will remove the f1 flag but this will need some deprecation cycle
=> test: fix test with newer llvm/clange

.github/workflows/tests.yml
Drop support for Python 3.7 and 3.8
=> ci: add CI for Python 3.12 and 3.13

src/pygccxml/declarations/calldef.py, tests/data/declarations_calldef.hpp, tests/data/test_dynamic_exception.hpp, tests/test_declarations.py, tests/test_dependencies.py, tests/test_dynamic_exception.py, tests/test_type_as_exception_bug.py
Fix failures when testes with c++17 and above
See https://github.com/CastXML/pygccxml/pull/227#issuecomment-2640919610
https://developers.redhat.com/articles/2021/08/06/porting-your-code-c17-gcc-11#exception_specification_changes From what I read here, there is no way to add exception specifications anymore (unless you use noexcept).
=> tests: extract dynamic exception tests

.github/workflows/tests.yml
Add/keep one test on ubuntu 20.04 as this is still supported
=> tests: move to ubuntu 22.04

.github/workflows/tests.yml, src/pygccxml/parser/project_reader.py
Keep one test on ubuntu 22.04 to test this older version
=> tests: move to ubuntu 24.04

.github/workflows/tests.yml, src/pygccxml/parser/config.py, tests/xml_generator.cfg
Clarify that we are using clang
Cleanup CI
Add more macos versions
=> ci: test all c++ versions

.github/workflows/tests.yml, src/pygccxml/declarations/container_traits.py
This pull request updates the `.github/workflows/tests.yml` file to include architecture specification and improve the setup process for CastXML on different operating systems. The most important changes include adding the `arch` field to the job matrix and splitting the CastXML setup steps based on the OS and architecture.
Updates to the job matrix:
* Added `arch: x86_64` to all job entries to specify the architecture for the build matrix. [[1]](diffhunk://#diff-1db27d93186e46d3b441ece35801b244db8ee144ff1405ca27a163bfe878957fR19-R43) [[2]](diffhunk://#diff-1db27d93186e46d3b441ece35801b244db8ee144ff1405ca27a163bfe878957fR52-R84) [[3]](diffhunk://#diff-1db27d93186e46d3b441ece35801b244db8ee144ff1405ca27a163bfe878957fR93-R109) [[4]](diffhunk://#diff-1db27d93186e46d3b441ece35801b244db8ee144ff1 …
=> PART 1: castxml 0.6.11 x86_64

.github/workflows/tests.yml
This pull request includes updates to the GitHub Actions workflow configuration for testing on MacOS. The changes involve specifying the architecture for different MacOS versions and updating the setup process for CastXML based on the architecture.
Updates to GitHub Actions workflow:
* [`.github/workflows/tests.yml`](diffhunk://#diff-1db27d93186e46d3b441ece35801b244db8ee144ff1405ca27a163bfe878957fR135-R141): Added architecture specification (`x86_64` and `arm64`) for MacOS versions 13 and 15 respectively.
* [`.github/workflows/tests.yml`](diffhunk://#diff-1db27d93186e46d3b441ece35801b244db8ee144ff1405ca27a163bfe878957fL185-R199): Updated the setup process for CastXML to download the appropriate version based on the MacOS version and architecture.
=> macos-15 / macos-13

.github/workflows/tests.yml, src/pygccxml/parser/project_reader.py
This pull request includes updates to the GitHub Actions workflow configuration to add support for Ubuntu ARM architectures. The most important changes include adding new job configurations for Ubuntu ARM and setting up CastXML for these new environments.
Updates to GitHub Actions workflow:
* [`.github/workflows/tests.yml`](diffhunk://#diff-1db27d93186e46d3b441ece35801b244db8ee144ff1405ca27a163bfe878957fR133-R149): Added job configurations for `ubuntu-22.04-arm` and `ubuntu-24.04-arm` with specific settings for architecture, compiler, and Python version.
* [`.github/workflows/tests.yml`](diffhunk://#diff-1db27d93186e46d3b441ece35801b244db8ee144ff1405ca27a163bfe878957fR201-R215): Added steps to set up CastXML for `ubuntu-22.04-arm` and `ubuntu-24.04-arm` environments, including downloading …
=> ubuntu arm

.github/workflows/tests.yml
Based on https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/ Testing only the build part for the time being, pypi upload will come in a second step
=> ci: build releases in pypi

.github/workflows/tests.yml
Based on
https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
=> ci: publish to pypi and sign packages
